# Generated by Django 2.0.1 on 2018-01-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('discipline', models.CharField(choices=[('UDH', 'Hebrew with UD'), ('YAPH', 'Hebrew with old dependencies')], default='UDH', max_length=4)),
                ('description', models.TextField()),
                ('example_sentence', models.CharField(max_length=200)),
                ('example', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PosCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('example_sentence', models.CharField(max_length=200)),
                ('example', models.TextField()),
            ],
        ),
    ]
